### ISSUE TITLE
Delete Acme

### ISSUE THREAD

**Issue by rkueny** [NicolasLAMBS/site_panneau_de_controle#1]
Supprimer la démo mise en place par Symfony

**Comment by NicolasLAMBS** [comment]
Démo supprimée.

**Comment by rkueny** [comment]
Ah bon ? https://github.com/NicolasLAMBS/site_panneau_de_controle/tree/master/src/Acme/DemoBundle

**Comment by NicolasLAMBS** [comment]
J'ai oublié de push la nouvelle version ><'

EDIT: voilà ! :)
